### ISSUE TITLE
Why does JOB_REF use the same token as REQUEST?

### ISSUE THREAD

**Issue by basdnguyen** [nestjs/bull#1013]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am confused about that since a Job and a Request are two different things, why are they using the same token.
When using `@Inject(REQUEST) private request: Request` inside a processor, it returns the same object as `@Inject(JOB_REF) jobRef: Job`

### Describe the solution you'd like

I would like to be able to use the request object inside my request-scoped processor

### What is the motivation / use case for changing the behavior?

A process-consuming request coming from a client, the nestjs server breaks down the request into small jobs to run later. But these jobs require access to the original request object, so that they can read the jwt payload and call other services to get data.

**Comment by kamilmysliwiec** [comment]
> I would like to be able to use the request object inside my request-scoped processor

This is impossible. Job processors are not tied to requests, they are triggered by jobs you add to the queue. The request may already be destroyed before your job even starts processing.

> I am confused about that since a Job and a Request are two different things

REQUEST != HTTP request. REQUEST provider in Nest is a dedicated provider that lets you register data for request-scoped providers.
