### ISSUE TITLE
job stalled more than allowable limit

### ISSUE THREAD

**Issue by DenisStephanov92** [nestjs/bull#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, I am trying to use this library to work with a bull in my nestjs application but almost each job is failing with error `job stalled more than allowable limit`

I also created question in SOF where I put my code: https://stackoverflow.com/questions/70261732/bulls-processor-in-nestjs-never-handled-queued-jobs

Can you tell me how to fix my code to start queues working? Thank you.

### Minimum reproduction code

https://stackoverflow.com/questions/70261732/bulls-processor-in-nestjs-never-handled-queued-jobs

### Expected behavior

I am expecting that when I add new job into queue, this job will be handled by processor based on passed queue and job options.

### Package version

0.4.2

### Bull version

4.1.1

### NestJS version

7.0.0

### Node.js version

14.15.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
