### ISSUE TITLE
#431 Reference bull doesn't throw error if redis is not available

### ISSUE THREAD

**Issue by sergeyampo** [nestjs/bull#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

A module doesn't throw any errors if Redis credentials are incorrect. It

### Minimum reproduction code

https://github.com/nestjs/bull/issues/431#issuecomment-924710826

### Steps to reproduce

https://github.com/nestjs/bull/issues/431#issuecomment-924710826

### Expected behavior

https://github.com/nestjs/bull/issues/431#issuecomment-924710826

### Package version

0.4.2

### Bull version

3.3

### NestJS version

8.1.2

### Node.js version

16.12.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by micalevisk** [comment]
@sergeyampo I believe you must handle connection errors by yourself with `@OnQueueError()` like:

```ts
import { Module } from '@nestjs/common'
import { BullModule, Processor, OnQueueError } from '@nestjs/bull'

@Processor('audio')
export class AudioConsumer {
  @OnQueueError()
  onError(err: Error) {
    console.error(err) // <<<<<<
  }
}

@Module({
  imports: [
    BullModule.forRoot({
      redis: {
        host: 'foo',
        port: 1234.
      },
    }),

    BullModule.registerQueue({
      name: 'audio',
    })
  ],
  providers: [AudioConsumer],
})
```
