### ISSUE TITLE
takeLock(), ReleaseLock() functionality

### ISSUE THREAD

**Issue by adikaladik** [nestjs/bull#108]
Since I'm going to use a lot of job consumers which will work in parallel I found job has to methods:

>     /**
>      * Releases the lock on the job. Only locks owned by the queue instance can be released.
>      */
>     releaseLock(): Promise<void>;
> 
>     /**
>      * Takes a lock for this job so that no other queue worker can process it at the same time.
>      */
>     takeLock(): Promise<number | false>;

Why I try to use that in my code, job fails with an erorr: '["Error: Missing lock for job 4 finished'
```
 @QueueProcess({ name: 'integration' })
  execute(job: Job<number>, callback: DoneCallback) {
    job.takeLock();
    this.logger.log(` start processing : ${job.id}`);
    this.userIntegrationService.processUserIntegrations(job.data).then(result => {
      job.releaseLock();
      callback(null, result);
    });
  }
```
Maybe I have a wrong understanding of that functuinality, but could someone advice what I do worng? Thanks!

**Comment by fwoelffel** [comment]
Hi @adikaladik 

`takeLock` and `releaseLock` both return `Promise`. You might have to await those calls:

```ts
 @QueueProcess({ name: 'integration' })
  async execute(job: Job<number>, callback: DoneCallback) {
    await job.takeLock();
    this.logger.log(` start processing : ${job.id}`);
    this.userIntegrationService.processUserIntegrations(job.data).then(async (result) => {
      await job.releaseLock();
      callback(null, result);
    });
  }
```

**Comment by adikaladik** [comment]
Hi, @fwoelffel are there any possible options which cause an error? When I added await to those calls new error happened:

> Missing lock for job 3 delayed

**Comment by fwoelffel** [comment]
Hi @adikaladik :wave: 
Could you provide me a repository reproducing your error? Have you checked Bull's issue tracker for a similar error? IMO that's not related to `nest-bull`.

**Comment by fwoelffel** [comment]
This may be related to
- https://github.com/OptimalBits/bull/issues/1243
- https://github.com/OptimalBits/bull/issues/789
- https://github.com/OptimalBits/bull/issues/700
- https://github.com/OptimalBits/bull/issues/647
