### ISSUE TITLE
Nest not binding Handlers to Bull jobs. Leaving them in the WAITING state permanently.

### ISSUE THREAD

**Issue by Mellywins** [nestjs/bull#1123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When creating a job and logging the object Queue.add({object}). The job does not have any handler attached to it.
```
EzyFS-NOTIFICATIONS       |   name: '__default__',
EzyFS-NOTIFICATIONS       |   queue: Queue {
EzyFS-NOTIFICATIONS       |     defaultJobOptions: { attempts: 3, removeOnComplete: true, removeOnFail: false },
EzyFS-NOTIFICATIONS       |     name: 'emailQueue',
EzyFS-NOTIFICATIONS       |     token: '4f5f9e4a-2b95-4095-8ddd-134ed91ed974',
EzyFS-NOTIFICATIONS       |     keyPrefix: 'bull',
EzyFS-NOTIFICATIONS       |     clients: [ [Redis] ],
EzyFS-NOTIFICATIONS       |     clientInitialized: true,
EzyFS-NOTIFICATIONS       |     _events: [Object: null prototype] {
EzyFS-NOTIFICATIONS       |       close: [Function],
EzyFS-NOTIFICATIONS       |       error: [Function (anonymous)]
EzyFS-NOTIFICATIONS       |     },
EzyFS-NOTIFICATIONS       |     _eventsCount: 2,
EzyFS-NOTIFICATIONS       |     _initializing: Promise { undefined },
EzyFS-NOTIFICATIONS       |     handlers: {},<---------------------------------------- Empty! Shouldn't be
EzyFS-NOTIFICATIONS       |     processing: [], <------------------------------------- Empty! Shouldn't be
EzyFS-NOTIFICATIONS       |     retrieving: 0,
```
I know it shouldn't be empty because i cloned the bull sample from the nest repo and ran the tests. These should hold the handler function.
I even copied the module from the sample and pasted it inside my microservice. I had the same issue. The @Processor() and @Process() didn't bind the function to the job.
I have proof that my Queue is being populated by job and they're all stuck in the waiting state, due to the absense of the handler.
```
127.0.0.1:6379> lrange bull:emailQueue:wait 0 -1
1) "13"
2) "12"
3) "11"
4) "10"
5) "9"
6) "8"
7) "7"
8) "6"
9) "5"
127.0.0.1:6379>
```
All of these are handler'less jobs. Same as the example above.

### Minimum reproduction code

https://github.com/Mellywins/EzyFS/tree/master/apps/notifications

### Steps to reproduce

Here is the module
```Javascript
@Module({
  imports: [
   .... 
    BullModule.forRootAsync({
      imports: [ConsulConfigModule],
      inject: [ConsulService],
      useFactory: async (consul: ConsulService<NotificationsConfig>) => {
        const config = await consul.get<NotificationsConfig>(
          ConsulServiceKeys.NOTIFICATIONS,
        );
        return {
          redis: {
            host: config.databases.redis.host,
            port: config.databases.redis.port,
          },
        };
      },
    }),
    BullModule.registerQueue({
      name: 'emailQueue',
      defaultJobOptions: {
        attempts: 3,
        removeOnComplete: true,
        removeOnFail: false,
      },
    }),
  ],
  controllers: [EmailController],
  providers: [EmailService, EmailProcessor], <--------- you can see that the processor is declared as a provider.
```
Here is the processor
```Javascript
@Processor('emailQueue')
export class EmailProcessor {
  private readonly logger = new Logger(this.constructor.name);

  constructor(
    private readonly mailerService: MailerService,
    private readonly emailService: EmailService,
  ) {
    this.logger.log('MailProcessor initialized');
  }

  @Process()
  async handleConfirmation(
    job: Job<{user: User; subject: string; templateName: string}>,
  ) {
    this.logger.log('Sending confirmation email');
  }
  }
```
This is how I'm pushing to the Queue:
```Javascript
    const job = await this.emailQueue.add({
      subject,
      templateName,
      user,
    });
```

### Expected behavior

The jobs should have the function decorated with @Process() as their handler. And the log message should appear.

### Package version

0.4.2

### Bull version

3.29.3

### NestJS version

8.2.5

### Node.js version

14.18.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

The function call to the controller is being invoked via gRPC. But i doubt it's relevent here.
The Project is a monorepo and the bull package is being used somewhere else. but i doubt its causing these issues.
Before you suggest going to discord. I did but the lack of responses made me think this issue might need more attention.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
