### ISSUE TITLE
Seperate Processor Strategy Outdate

### ISSUE THREAD

**Issue by stevenolay** [nestjs/bull#1142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The strategy for separate processes appears to be broken in NestJS `^8.0.0`. I think it's because the compilation strategy uses webpack, and minifies the whole source into a single main.js file. So the path based import does not work. 

When i run the example detailed here(https://docs.nestjs.com/techniques/queues#separate-processes
) 1:1 I get the following error. 

```
Error: File **/dist/apps/**/processor.js does not exist
```

Any idea how I can get this stuff to work?

Thanks!

### Minimum reproduction code

https://docs.nestjs.com/techniques/queues#separate-processes

### Expected behavior

I expect to be able to set up a job processor that can run in a separate process. 

### Package version

^0.4.0

### Bull version

3.18.0

### NestJS version

^8.0.4

### Node.js version

14

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
I didn't manage to reproduce this with this sample: https://github.com/nestjs/nest/tree/master/sample/26-queues (and applying the changes that the docs suggests).

> I think it's because the compilation strategy uses webpack

`nest build` don't use Webpack by default.

I'm pretty sure you just need to adjust that `join(__dirname, 'processor.js')` statement

**Comment by stevenolay** [comment]
Okay I will try this and see if it helps me understand what tweaks I need to make to mine.

I am using the NestJS Monorepo functionality. 

Not sure if that's why it's using webpack.

**Comment by stevenolay** [comment]
Yeah, so looks like in monorepo mode the default is webpack: 
https://docs.nestjs.com/cli/monorepo#global-compiler-options

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/9903968/156910231-19b9261a-089d-4217-a565-45a1570db17e.png">

**Comment by micalevisk** [comment]
so this is probably be a misconfiguration on your side. You can go to the Discord to ask on how to properly use webpack to such scenario. I have no experience on this :/

**Comment by stevenolay** [comment]
@micalevisk Yeah, I already popped a question in the discord and got no traction. So i filed in here instead. 😅

**Comment by stevenolay** [comment]
I'm going to go ahead and close this, I switched my compilation strategy from Webpack to TSC for the project in my monorepo that needed to run Sandboxed Processes. 

I can't think of a sane way to get this stuff to work with webpack, so this strategy will have to suffice. 

Thanks.
