### ISSUE TITLE
[Feature Request] Allow worker process jobs without register queue

### ISSUE THREAD

**Issue by xiaoyu-tamu** [nestjs/bull#1144]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Thank you for supporting BullMQ officially, I can finally use this lib instead of my own impl.

My use case is I have two separate apps,  producer and consumer

I noticed that in my consumer app, I must register the queue otherwise my worker processor wont get called.

```ts
// the process never execute

import { BullModule, Processor, WorkerHost } from '@nestjs/bullmq';
import { Module } from '@nestjs/common';

@Processor({ name: 'QUEUE1' })
export class TestWorker extends WorkerHost {
  async process(): Promise<void> {}
}

@Module({
  imports: [BullModule.forRoot({})],
  providers: [TestWorker],
})
export class TestWorkerModule {}
```

```ts
// this works fine since i register the queue

import { BullModule, Processor, WorkerHost } from '@nestjs/bullmq';
import { Module } from '@nestjs/common';

@Processor({ name: 'QUEUE1' })
export class TestWorker extends WorkerHost {
  async process(): Promise<void> {}
}

@Module({
  imports: [BullModule.forRoot({}),BullModule.registerQueue({name:"QUEUE1"})],
  providers: [TestWorker],
})
export class TestWorkerModule {}

```

But in my consumer app, I don't need the queue.

### Describe the solution you'd like

worker can work independently without a queue registered.

```ts
import { BullModule, Processor, WorkerHost } from '@nestjs/bullmq';
import { Module } from '@nestjs/common';

@Processor({ name: 'QUEUE1' })
export class TestWorker extends WorkerHost {
  async process(): Promise<void> {}
}

@Module({
  imports: [BullModule.forRoot({})],
  providers: [TestWorker],
})
export class TestWorkerModule {}
```

### What is the motivation / use case for changing the behavior?

It doubles the redis connections needed for each worker.

in native bullmq, 4 connection for producer (scheduler + queue), 2 connection for each consumer (worker).

in nestjs bullmq, 4 connection for producer (scheduler + queue), 4 connection for each consumer (queue + worker)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/bull/pull/1148
