### ISSUE TITLE
tslib dependency is not declared

### ISSUE THREAD

**Issue by Grmiade** [nestjs/bull#1151]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

0.4.2 -> 0.5.2

### Describe the regression

https://github.com/nestjs/bull/blob/master/packages/tsconfig.build.json#L8
Since you set `importHelpers` to `true`, you should declare `tslib` as a dependency of each package

```
Error: @nestjs/bull tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

### Minimum reproduction code

```ts

```

### Expected behavior

`tslib` package is declared as a dependency

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
