### ISSUE TITLE
[bullmq] Add providers for Workers

### ISSUE THREAD

**Issue by tolgap** [nestjs/bull#1181]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In `@nest/bull`, you could easily override just the `Queue` class and it's processor by doing `.overrideProvider(getQueueToken(queueName)).useValue(myQueueMock)`. It was something handy for e2e tests, when you weren't necessarily testing the queue/worker logic.

In `@nest/bullmq`, you can override `Queue` and `QueueScheduler`, but not `Worker`.

### Describe the solution you'd like

It would be nice to add providers for `Worker`s. Allow full mocking of the entire `bullmq` "logic".

### What is the motivation / use case for changing the behavior?

It is nice to have for e2e tests, when you weren't necessarily testing the queue/worker logic.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? @tolgap 🙌

**Comment by tolgap** [comment]
Well, I seem to have jumped the gun on this issue... All I would have to do is `.overrideProvide(MyConsumer).useValue(myConsumerMock)`. Because you have to provide the processors yourself in your modules in the `provide` array.

By overriding queue provider in your tests, you can already mock `processors` with mock functions or mock files.

So this is actually a non-issue for me.
