### ISSUE TITLE
@OnQueueActive does not allows cancel jobPromise neither is been executed before process the job

### ISSUE THREAD

**Issue by felinto-dev** [nestjs/bull#1183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The decorator `@OnQueueActive()` currently is being executed AFTER the job is processed and does not allow the job to be canceled.

```ts
	@OnQueueActive()
	async mustCancelJob(job: Job, jobPromise: JobPromise) {
		this.logger.debug('Starting job process...');
		jobPromise.cancel()
	}

	@Process('transcode')
	async handleTranscode(job: Job) {
		this.logger.debug('Start transcoding...');
		this.logger.debug(job.data);
		this.logger.debug('Transcoding completed');
	}
```

I receive this error from the console:

```
[Nest] 4963  - 04/04/2022, 5:28:47 AM   DEBUG [AudioProcessor] Start transcoding...
[Nest] 4963  - 04/04/2022, 5:28:47 AM   DEBUG [AudioProcessor] Object:
{
  "file": "audio.mp3"
}

[Nest] 4963  - 04/04/2022, 5:28:47 AM   DEBUG [AudioProcessor] Transcoding completed
[Nest] 4963  - 04/04/2022, 5:28:47 AM   DEBUG [AudioProcessor] Starting job process...

/workspace/src/audio/audio.processor.ts:12
                jobPromise.cancel()
             ^
TypeError: jobPromise.cancel is not a function
    at AudioProcessor.mustCancelJob (/workspace/src/audio/audio.processor.ts:12:14)
    at Queue.emit (node:events:520:28)
    at Object.module.exports.emitSafe (/workspace/node_modules/bull/lib/utils.js:50:20)
    at Queue.processJob (/workspace/node_modules/bull/lib/queue.js:1165:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It is possible to realize that:
1. "Starting jog process..." has been executed AFTER the job is processed.
2. Is not possible to cancel the job.

### Minimum reproduction code

https://github.com/felinto-dev/nestjs-bull-bug

### Steps to reproduce

1. yarn install
2. yarn start:dev
3. Access in browser: [http://localhost:3000/audio/transcode](http://localhost:3000/audio/transcode)
4. Check the console log and this file:
https://github.com/felinto-dev/nestjs-bull-bug/blob/master/src/audio/audio.processor.ts

### Expected behavior

I expected the code inside the method "mustCancelJob" to run before "handleTranscode" and be possible to cancel the job as the documentation says is possible:

https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#global-events

```ts
.on('active', function (job, jobPromise) {
  // A job has started. You can use `jobPromise.cancel()`` to abort it.
})
```

### Package version

0.5.4

### Bull version

4.8.1

### NestJS version

8.4.3

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by felinto-dev** [comment]
pinging @fwoelffel
because you implemented the PR, maybe would check it
https://github.com/nestjs/bull/issues/53#issue-438733972

**Comment by kamilmysliwiec** [comment]
This issue does not seem to be related to the `@nestjs/bull` wrapper but rather to `bull` package itself.
