### ISSUE TITLE
@OnQueueActive does not allows cancel jobPromise neither is been executed before process the job

### ISSUE THREAD

**Issue by felinto-dev** [nestjs/bull#1184]
This issue does not seem to be related to the `@nestjs/bull` wrapper but rather to `bull` package itself.

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/bull/issues/1183#issuecomment-1087180341_

**Comment by felinto-dev** [comment]
Could you give more details? You closed the issue and I can't ask you.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
