### ISSUE TITLE
[bullmq] Wrong types on queue limiter

### ISSUE THREAD

**Issue by squareloop1** [nestjs/bull#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When registering a queue with a limiter the types only allow for a `groupKey: string` but not for `max: number` & `duration: number`.

### Minimum reproduction code

https://codesandbox.io/s/nestjs-forked-y26vp2?file=/src/app.module.ts

### Steps to reproduce

1. See attached reproduction in codesandbox
2. See the type error on async queue registration in `app.module.ts`
```
Type '{ max: number; duration: number; }' is not assignable to type '{ groupKey: string; }'.
  Object literal may only specify known properties, and 'max' does not exist in type '{ groupKey: string; }'.ts(2322)
```

### Expected behavior

It should be possible to register a queue with a limiter without `groupKey`.

### Package version

0.04

### Bull version

1.79.0

### NestJS version

8.4.4

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
<img width="609" alt="image" src="https://user-images.githubusercontent.com/23244943/162726586-e0427a11-cbd6-46b4-b480-6c7d85988f17.png">

This interface comes from the `bullmq` package.
