### ISSUE TITLE
Passing Redis connection string when registering module or queue.

### ISSUE THREAD

**Issue by alko89** [nestjs/bull#1307]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Based on the code here:

https://github.com/nestjs/bull/blob/master/packages/bull/lib/bull.providers.ts#L24

It seems that redis could also be passed as a string with Redis URL instead of `RedisOptions`, however registering a queue with redis param as a string throws a type error.

![image](https://user-images.githubusercontent.com/2822030/175319153-8b52ede4-90b3-4574-99c9-b0e51bb91d08.png)

### Describe the solution you'd like

Allow passing Redis params as a connection string.

### What is the motivation / use case for changing the behavior?

One environment variable (url) instead of many (host, port, username, passowrd).

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/bull/pull/1308

**Comment by andreialecu** [comment]
I am leaving this here for others that may run into this. 

#1308 introduced a breaking change that I don't see mentioned anywhere.

We were using the `redis` property previously to pass the actual URL. It seems the PR renamed it to `URL`.

Not sure why this was necessary.

![image](https://user-images.githubusercontent.com/697707/186225149-6f92399d-2a57-4150-82a2-a02f194c1b77.png)

The previous type seems to have been correct, and it included `string`, so I'm not sure what this issue originally reported.
