### ISSUE TITLE
Nest crashs on unhandled exception in bull process

### ISSUE THREAD

**Issue by LucCADORET** [nestjs/bull#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When an unhandled exception happens in a bull process, it crashes the whole Nest app, despire having the node option `--unhandled-rejections=warn-with-error-code`

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/26-queues

### Steps to reproduce

1. Get the official sample code for bull queues
2. Edit the transcode process in `audio.processor.ts` to throw an unhandled exception, e.g.:
```
  @Process('transcode')
  handleTranscode(job: Job) {
    setInterval(() => {
      throw new Error("unhandled");
    }, 0);
    this.logger.debug('Start transcoding...');
    this.logger.debug(job.data);
    this.logger.debug('Transcoding completed');
  }
```
3. Compile the code with `tsc`
4. Run the code: `node dist/main.js --unhandled-rejections=warn-with-error-code`
5. Launch the process by doing e.g.: `curl -X POST http://localhost:3000/audio/transcode`
6. The code should crash and exit

### Expected behavior

If provided the option `--unhandled-rejections=warn-with-error-code` by node, unhandled exception shouldn't exit node.

### Package version

0.4.2

### Bull version

3.29.3

### NestJS version

8.2.3

### Node.js version

16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
I guess this is expected because unhandled exceptions aren't supposed to be handled by nestjs. Instead you should handle them in your app
