### ISSUE TITLE
connect to redis cluster

### ISSUE THREAD

**Issue by BEIIKS** [nestjs/bull#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, 
im currently migrating my project to redis cluster and im trying to connect my code to the redis cluster i created.
i can`t find any documentation on how to connect to a redis cluster using the @nestjs/bull package.
do the libarary support the usage of redis cluster? and what is the recommended way to implement that usage?

### Minimum reproduction code

..

### Expected behavior

the documentation will inclide a code snippet explaining how to connect to a redis cluster

### Package version

8.1.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I guess you need to search on how to connect to a redis cluster using `bull`
