### ISSUE TITLE
Cannot connect to remote redis instance

### ISSUE THREAD

**Issue by bingomanatee** [nestjs/bull#1353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am using BullModule in nest.js. 

when I connect to a local redis it works:

    const REDIS = {
      host: 'localhost', 
    };

    @Module({
      imports: [
        TaskTypesModule,
        TasksModule,
        ScheduleModule.forRoot(),
        BullModule.forRoot({
          // @ts-ignore
          redis: REDIS,
        }),
      ],
      controllers: [AppController],
      providers: [AppService, PrismaService],
    })
    export class AppModule {}

But when I connect to a remote system 

    const REDIS = {
      host: process.env.REDIS_ENDPOINT,
      port: process.env.REDIS_PORT,
      password: process.env.REDIS_PASSWORD,
    };

with env file

    REDIS_USERNAME=default
    REDIS_PASSWORD=p----------------------S
    REDIS_ENDPOINT=redis-1xxxxx4.c261.us-east-1-4.ec2.cloud.redislabs.com
    REDIS_PORT=1xxxxx4

it doesn't write to the redis queue; 

So - bottom line - how to configure the redis node for a remote connection in Bull? what is the proper way to format a remote redis URL?

## Bull version

    "@nestjs/bull": "^0.6.0",
    "bull": "^4.8.4",

## Additional information

by way of comparison, I can connect via redisight:

 ! [1](https://i.stack.imgur.com/VYuvU.png)

### Minimum reproduction code

https://github.com/bingomanatee/workworkwork

### Expected behavior

connect, uses remote repo for redis

### Package version

0.6.0

### Bull version

4.8.4

### NestJS version

8.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
have you tried hard coding the credentials instead of using `process.env`?

**Comment by iiAku** [comment]
Hello,
I've seen this https://github.com/nestjs/bull/issues/453 and I was basically experiencing the exact same issue as @bingomanatee mentioned.

Locally everything is fine, but if I'm using remote credentials it does not work.

I believe it comes from the fact that often remote Redis instances are accessed securely. So I presume you are trying to connect in a secure way and it hangs.

So to make it work you have to specify the `tls` connection credentials props within the redis configuration, and you need to keep the initial one. Handle it your way to make sure you have it or not based on your stages.

Something like this should work:

```
import { ConfigModule, ConfigService } from '@nestjs/config';

import { AppController } from './app.controller';
import { AppService } from './app.service';
import { BullModule } from '@nestjs/bull';
import { Module } from '@nestjs/common';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    BullModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => {
        const credentials = {
          username: configService.get('REDIS_USER') || '',
          password: configService.get('REDIS_PASSWORD') || '',
          host: configService.get('REDIS_HOSTNAME') || 'localhost',
          port: +configService.get('REDIS_PORT') || 6379,
        };
        return {
          redis: {
            ...credentials,
            tls:
              //handle it the way you want based on your stages
              configService.get('NODE_ENV') === 'development'
                ? {}
                : credentials,
          },
        };
      },
      inject: [ConfigService],
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}


```

**Comment by bingomanatee** [comment]
ok thanks - but the "host" property - do you use the redis:// prefix? do you include the username/password? what EXACTLY is your host URL property formed as?

**Comment by iiAku** [comment]
You can double check the type if you are using typescript. If that note the case here the details:
First redis props is optional:

`redis?: Redis.RedisOptions | undefined;`

Then RedisOptions is full type here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts#L1997

```
    interface RedisOptions {
        port?: number | undefined;
        host?: string | undefined;
        /**
         * 4 (IPv4) or 6 (IPv6), Defaults to 4.
         */
        family?: number | undefined;
        /**
         * Local domain socket path. If set the port, host and family will be ignored.
         */
        path?: string | undefined;
        /**
         * TCP KeepAlive on the socket with a X ms delay before start. Set to a non-number value to disable keepAlive.
         */
        keepAlive?: number | undefined;
```

Then the tls props from Redis option is a `interface ConnectionOptions extends SecureContextOptions, CommonConnectionOptions` 
You have full type here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/tls.d.ts#L516

So to answer your question tls will take the basic and my host value is full hostname without the rediss thing, rediss uri is a connection string or commonly called uri.

```
        host?: string | undefined;
        port?: number | undefined;
```
My previous answer is a little bit inaccurate since providing only host and port should be sufficient.

I'm edditing it to make it more accurate.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
