### ISSUE TITLE
Event listeners for request-scoped consumers

### ISSUE THREAD

**Issue by leonardbinet** [nestjs/bull#1413]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

My end-goal is to track and log jobs completions / failures (to feed datadog).

I tried using event listeners, but found out that they don't work with request-scoped consumers.

### Describe the solution you'd like

Just have the same behavior as for non-scoped consumers.

### What is the motivation / use case for changing the behavior?

Log jobs completions / failures on scope-requests consumers.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
