### ISSUE TITLE
Update `bullmq` dependency to v2.0.0

### ISSUE THREAD

**Issue by tolgap** [nestjs/bull#1414]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

BullMQ recently released version 2. It contains breaking changes. Namely the removal of `QueueScheduler` class. The `QueueScheduler` class isn't needed anymore to support delayed jobs.

### Describe the solution you'd like

- Upgrade the `peerDependency` to `"bullmq": "^2.0.0"`
- Remove usage of `QueueScheduler`.

### Teachability, documentation, adoption, migration strategy

https://github.com/taskforcesh/bullmq/releases/tag/v2.0.0

### What is the motivation / use case for changing the behavior?

Have an upgrade path for my project that uses `@nestjs/bullmq`.

**Comment by xiaoyu-tamu** [comment]
Hi, @kamilmysliwiec someone already made a PR.
