### ISSUE TITLE
Ability to disable job processing

### ISSUE THREAD

**Issue by leonardbinet** [nestjs/bull#1416]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In our current setup, we run two types of instances of nestjs:
- `backend` instances that serve our application
- `admin-backend` instances that serve our admin dashboard (via adminJS)

Our `admin-backend` imports nestjs modules of our `backend` application (notably to give the ability to trigger jobs), and thus processes bullmq jobs.

We would like to avoid such behavior.

### Describe the solution you'd like

To avoid this, it would be nice to be able to disable processing of jobs in `admin-backend` instances using an environment variable that would be passed to `BullModeul.forRoot` method.

### What is the motivation / use case for changing the behavior?

Explained in `Is your feature request related to a problem? Please describe it`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
