### ISSUE TITLE
Single processor for multiple queues

### ISSUE THREAD

**Issue by snigdha920** [nestjs/bull#1458]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hello all! Firstly, thank you Nest for a great job! 

A limitation in bullqueue is that concurrency for named processors of a single queue stacks up. 

Hence I have had to create multiple queues (for this eg, let's take 7) to manage concurrency for each named processors.

Now, I want to perform the same method whenever a job on any of these queues is `active`, `completed`, etc. So the same methods to be invoked on `OnQueueActive`, `@OnQueueCompleted`, etc.

But since the jobs are on different queues, I need to create 7 different classes with the `Processor` decorator for each queue, all having the same class body. That is a cumbersome and a lot of boilerplate code duplication. :( 

### Describe the solution you'd like

Instead of having 7 different classes with `@Processor(Queue-1)`, `@Processor(Queue-2)`, etc. having essentially the same class body, is there a way we can just define one class as a processor for the different queues? 

So something like:

```typescript
 @Processor(['Queue-1', 'Queue-2', ...])
```

Well, I tried to be smart and did the following: 
1. Created a dynamic module, let's call it `EventProcessorModule`, which took in options of the shape: 

```typescript
{
    queueNameOrOptions: ProcessorOptions,
}
```

2. Injected them in the `EventProcessorService` and accessed it in the `EventProcessorService` constructor as follows:
(this basically does what the `@Processor` decorator does)
```typescript
const queueNameOrOptions = this.options.queueNameOrOptions;
const processorOptions =
      queueNameOrOptions && typeof queueNameOrOptions === 'object' ? queueNameOrOptions : { name: queueNameOrOptions };

    SetMetadata(SCOPE_OPTIONS_METADATA, processorOptions)(EventProcessorService);
    SetMetadata(BULL_MODULE_QUEUE, processorOptions)(EventProcessorService);

```

When I do: 
```typescript
{
EventProcessorModule.register({queueNameOrOptions: 'Queue-1'}),
EventProcessorModule.register({queueNameOrOptions: 'Queue-2'}),
EventProcessorModule.register({queueNameOrOptions: 'Queue-3'}),
...
}
```

This doesn't work because the `SCOPE_OPTIONS_METADATA`, `BULL_MODULE_QUEUE` get set to the last instance(?) of the `EventProcessorService`, so only the event listeners for Queue-3 work. 

This could also be implemented on an event handler level, so: 

```typescript 
@OnQueueActive({['Queue-1', 'Queue-2', ...]})
```

### Teachability, documentation, adoption, migration strategy

It's pretty simple, if we want the same processor or event handlers for different queues, we would specify the queue name in the array. 

### What is the motivation / use case for changing the behavior?

It makes the package better because it would make handling the limitations of the underlying technology easier. 

I would be happy to create a PR for this!

**Comment by kamilmysliwiec** [comment]
> But since the jobs are on different queues, I need to create 7 different classes with the Processor decorator for each queue, all having the same class body. That is a cumbersome and a lot of boilerplate code duplication. :(

What about creating a base class that other processor classes inherit from?

**Comment by snigdha920** [comment]
> > But since the jobs are on different queues, I need to create 7 different classes with the Processor decorator for each queue, all having the same class body. That is a cumbersome and a lot of boilerplate code duplication. :(
> 
> What about creating a base class that other processor classes inherit from?

Indeed, that is what I am implementing currently. Going to use [property based injections](https://docs.nestjs.com/providers#property-based-injection) to reduce the boilerplate code. 

I was hoping for an easier way to do this though, because every time I add a new type of job: I need to create a class, extend it, register the provider vs just adding an item in an array.

**Comment by snigdha920** [comment]
What do you think?

**Comment by kamilmysliwiec** [comment]
AFAIR, adding annotated methods, as in the following example:

```
@OnQueueFailed()
async onQueueFailed(job: Job) {
 await this.failedBaseClassFn(job);
}
```

on the base class (AbstractProcessor) should be sufficient 🤔

**Comment by snigdha920** [comment]
> 

Ah yes, you're totally right! That works well along with [property based injections](https://docs.nestjs.com/providers#property-based-injection) to keep the boilerplate code to a minimum. 

I'll close the ticket since this is a good enough solution for me, thank you for your help! 😄
