### ISSUE TITLE
Nest could not find BullQueue_default element

### ISSUE THREAD

**Issue by carloserocha** [nestjs/bull#1480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

I'm trying to use bull but following the documentation, I always get the following error.

### Minimum reproduction code

https://stackblitz.com/edit/typescript-u942dy

### Expected behavior

Just run =(

### Package version

0.6.2

### Bull version

4.8.4

### NestJS version

9.0.1

### Node.js version

v16.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

`C:\Users\carlos.rocha\job\sync-api\node_modules\@nestjs\core\injector\instance-links-host.js:15
            throw new unknown_element_exception_1.UnknownElementException(this.getInstanceNameByToken(token));
                  ^
Error: Nest could not find BullQueue_default element (this provider does not exist in the current context)
    at InstanceLinksHost.get (C:\Users\carlos.rocha\job\sync-api\node_modules\@nestjs\core\injector\instance-links-host.js:15:19)`

**Comment by micalevisk** [comment]
Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction). You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by carloserocha** [comment]
> Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction). You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

okay, done

**Comment by carloserocha** [comment]
https://discord.com/channels/520622812742811698/811732928517767179/1042436284305641485
