### ISSUE TITLE
Support metrics parameters in workers and/or queues

### ISSUE THREAD

**Issue by rbialek** [nestjs/bull#1550]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Accept metrics param in queue/worker creation.

### Describe the solution you'd like

Extend BullModuleOptions to work with https://docs.bullmq.io/guide/metrics 

BullModule.registerQueue({
      name: 'someName',
      limiter: { ...    },
      metrics: {
         maxDataPoints: Queue.utils.MetricsTime.TWO_WEEKS,
      },
    }),

### What is the motivation / use case for changing the behavior?

Support bullmq metrics

**Comment by manast** [comment]
Btw, Metrics are available both for Bull and BullMQ.

**Comment by roggervalf** [comment]
Good morning @rbialek, as part of https://docs.bullmq.io/guide/metrics, metrics options is part of worker options, in this case you can pass metricts to Processor like this:
```ts
@Processor('queueName', {
  metrics: {
    maxDataPoints: 2000,
  }
})
```
could you please try it?

**Comment by UzalKhadka** [comment]
@manast @roggervalf I am using Bull queue and need to enable the metrics and collect the last 2 week's data points. How do I enable it using NestJS ?
Before, while using Express and Bull, I was creating Queues like this:
`new Queue("emailQueue", redis_URL, {
            metrics: {
              maxDataPoints: Queue.utils.MetricsTime.TWO_WEEKS,
            },
          });`

Now, while using NestJS, I am creating Queues like this:
`BullModule.registerQueue({
      name: 'emailQueue',
    }),`
    
How to enable the metrics option using the NestJS approach? I did not find any solutions in the docs / forums.

**Comment by rbialek** [comment]
@roggervalf Unfortunately, the nestjs @Processor decorator does not allow metrics param.

**Comment by UzalKhadka** [comment]
@rbialek for Bull, I think the metrics params are sent while the creation of a queue (while using Bull not Nestjs/bull). Might be same for BullMQ. I have not used that.

**Comment by vinaya-procore** [comment]
> @roggervalf Unfortunately, the nestjs `@Processor` decorator does not allow metrics param.

The `Processor` decorator accepts [WorkerOptions](https://github.com/nestjs/bull/blob/master/packages/bullmq/lib/decorators/processor.decorator.ts#L33) argument, which inclueds the `metrics` object.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
