### ISSUE TITLE
update docs to 

### ISSUE THREAD

**Issue by laurencefass** [nestjs/bull#1565]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This is a document related feature request. 

I assume that the existing documentation at https://docs.nestjs.com/techniques/queues is relevant whether I install Bull or BullMQ. Is that correct?

If that is the case how can I make use of the new features present in BullMQ not present in Bull? i.e. flows (+ quite a lot of other great features).

Are document updates roadmapped for nestjs/BullMQ?

Thanks

### Describe the solution you'd like

Well documented instructions for installing and using nestjs/bullmq

### What is the motivation / use case for changing the behavior?

There is only one source of documentation for two separate versions of Bull that perform quite differently with different APIs.

**Comment by micalevisk** [comment]
related with https://github.com/nestjs/docs.nestjs.com/issues/2353
