### ISSUE TITLE
Docker - Missing handler for job type

### ISSUE THREAD

**Issue by ahmadarif** [nestjs/bull#160]
Missing handler often occurs when running in docker (with node alpine and puppeteer), I need to retry the job until the job can be taken by Queue (4 attempts). After 4 times hit the retry button (Arena Dashboard) task processed by the queue, and the process is completed.
Is there any additional configuration for running using docker?

NestJS version: **6.0.2**
nest-bull: **0.8.1**

![image](https://user-images.githubusercontent.com/10185374/63180457-84e94780-c078-11e9-9136-dae2aa38b5d7.png)

**Comment by fwoelffel** [comment]
That's weird, I'm using `nest-bull` in production. The setup seems to be the same as you: everything runs inside docker containers. I haven't encountered such issue yet.
Could anyone confirm this behavior?
