### ISSUE TITLE
Decorator InjectQueue has error with TS 5.X

### ISSUE THREAD

**Issue by andreyddk** [nestjs/bull#1639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

typescript 5.0.2
@nestjs/bull - latest

If add decorator InjectQueue in constructor then you see error.

```
Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.
```

I guess the problem in returning type of decorator (ParameterDecorator), because another decorator no have same error (Inject)

### Minimum reproduction code

https://github.com/andreyddk/nestjs-bull-inject-queue-decorator-failure

### Steps to reproduce

npm i
npm run watch

### Expected behavior

```
src/playground/playground.service.ts(10,6): error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.
```

### Package version

0.6.3

### Bull version

4.10.4

### NestJS version

9.3.12

### Node.js version

18 lts

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

```
error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.

93     @InjectQueue('TEST_QUEUE')
```

Solution could be removing returning type ParameterDecorator or make the same type of nestjs Inject.
Example:

```
const InjectQueueV2 = (
  name?: string
): ((
  target: object,
  key: string | symbol | undefined,
  index?: number | undefined
) => void) => Inject(getQueueToken(name));
```
or

`const InjectQueueV2 = (name?: string) => Inject(getQueueToken(name));`

**Comment by kamilmysliwiec** [comment]
`InjectQueue` uses `Inject` under the hood:

![image](https://user-images.githubusercontent.com/23244943/227455259-b8336799-4cf8-400a-84df-b1d9999fcbf0.png)

which was already updated to support TS 5.0. Update to the latest version of `@nestjs/common` and the error will be gone
