### ISSUE TITLE
Jest test suite not exiting when upgrading BullMQ to 3.8.0

### ISSUE THREAD

**Issue by rossmotley** [nestjs/bull#1650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When upgrading BullMQ from 3.7.2 to 3.8.0, my Jest tests are still passing, but they hang for ~30 before exiting.

It seems to be related to the introduction of the stalled timer - 
https://github.com/taskforcesh/bullmq/compare/v3.7.2...v3.8.0

### Minimum reproduction code

https://github.com/rossmotley/nest-bull-test-issue

### Steps to reproduce

See repo above.

### Expected behavior

Tests should exit immediately.

### Package version

1.1.0

### Bull version

>=3.8.0

### NestJS version

9.3.12

### Node.js version

18.12

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [x] Linux

**Comment by rossmotley** [comment]
I investigated this a bit further, it was happening for some of my tests but not others. It seemed to be that the bullmq stalled job timer was not being cleared properly when the queue workers were closed between e2e tests, possibly because of how jest was resetting the module state.

I'm not sure if the problem is coming from bullmq or the nestjs module, but changes to the timing conditions in my code mean it doesn't manifest anymore for me.

I have put together a minimal repo to reproduce the issue at https://github.com/rossmotley/nest-bull-test-issue and it is still happening there for me.

**Comment by roggervalf** [comment]
hi @rossmotley, you can upgrade your dependency at least from https://github.com/taskforcesh/bullmq/releases/tag/v3.12.1

**Comment by rossmotley** [comment]
hi @roggervalf, my example repo has `bullmq` at `3.15.5` already.

**Comment by rossmotley** [comment]
hi @roggervalf, I took a further look, and it seems that upgrading from `3.15.5` to `3.15.6` has resolved the issue. https://github.com/taskforcesh/bullmq/compare/v3.15.5...v3.15.6
