### ISSUE TITLE
[feature] ability to listen to queue events in one single class

### ISSUE THREAD

**Issue by ThallesP** [nestjs/bull#1655]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently to listen to events (failed, completed, etc) in `@nestjs/bullmq` you've to implement `QueueEventsHost` and add the necessary decorator `@OnQueueEvent('failed')`.

- The problem is when you've already implemented `WorkerHost`, you can't implement any other classes, then the events can't be in a single class as it was in `@nestjs/bull` package.

This is not possible anymore in `@nestjs/bullmq`:
```ts
import { Processor, Process, OnQueueActive } from '@nestjs/bull';
import { Job } from 'bull';

@Processor('audio')
export class AudioConsumer {

  // process the queue and also listen to events
  @OnQueueActive()
  onActive(job: Job) {
    console.log(
      `Processing job ${job.id} of type ${job.name} with data ${job.data}...`,
    );
  }
  ...
```

### Describe the solution you'd like

I would like some way to listen to events in one single class, maybe removing the need for `QueueEventsHost`.

For my use case, I thought of having a global event listener, that listens to every queue and its events.

For example: `@QueueEventsListener('*') // or maybe just undefined`

### What is the motivation / use case for changing the behavior?

I don't think it's a good approach as it would need to create a class just to listen to events, for example in my use case, I want to report errors to a log service, and I would need to create a single class for all `queue` just to listen to one event.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
