### ISSUE TITLE
Can't connect with Redis Cluster

### ISSUE THREAD

**Issue by hashcott** [nestjs/bull#1663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```js
 BullModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        createClient: () =>
          new Redis.Cluster(
            configService
              .get<string>(`db.redis`)
              .split(',')
              .map((host) => ({ host, port: 6379 })),
          ),
      }),
      inject: [ConfigService],
    }),
    BullModule.registerQueue({
      name: 'typo-index',
    }),
```

error 
```
Type '(configService: ConfigService) => Promise<{ createClient: () => Redis.Cluster; }>' is not assignable to type '(...args: any[]) => BullRootModuleOptions | Promise<BullRootModuleOptions>'.
  Type 'Promise<{ createClient: () => Cluster; }>' is not assignable to type 'BullRootModuleOptions | Promise<BullRootModuleOptions>'.
    Type 'Promise<{ createClient: () => Cluster; }>' is not assignable to type 'Promise<BullRootModuleOptions>'.
```

### Minimum reproduction code

https://gist.github.com/hashcott/8e84adb163acc83b35da4090c2eff476

### Expected behavior

...

### Package version

0.6.3

### Bull version

4.10.4

### NestJS version

9.0.0

### Node.js version

16.19.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
