### ISSUE TITLE
support Manual rate-limit of bullmq in `@nestjs/bullmq`

### ISSUE THREAD

**Issue by grimmer0125** [nestjs/bull#1694]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I saw bullmq has a feature to customize the rate-limit by using `throw Worker.RateLimitError();`, and the reference is https://docs.bullmq.io/bullmq-pro/groups/rate-limiting#manual-rate-limit. I do not see the equivalent feature in `@nestjs/bullmq`.

### Describe the solution you'd like

support throwing some equivalent error like `throw Worker.RateLimitError();` in `async process`. 

### What is the motivation / use case for changing the behavior?

Some need to manually customize the bull's rate limit behavior, rather than the normal setup in the class decorator. 
```
@Processor('audio', {
  concurrency: 80,
  limiter: {
    max: 1,
    duration: 3000
  },
})
```

**Comment by kamilmysliwiec** [comment]
```typescript
BullModule.workerClass = WorkerPro
```

and then you should be able to use `throw Worker.RateLimitError()`

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
