### ISSUE TITLE
Not closing connection as expected

### ISSUE THREAD

**Issue by simplenotezy** [nestjs/bull#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

According to @jmcdo29, this library doesn't implement an `OnModuleClose` to handle closing the connection to bull or redis when the application shuts down.

### Minimum reproduction code

https://github.com/simplenotezy/bullmq-and-commander

### Steps to reproduce

1. `docker-compose up`
2. npm run build
3. cli basic
4. See that the terminal hangs forever

### Expected behavior

The app should shutdown when closed

### Package version

1.1.0

### Bull version

^3.15.4

### NestJS version

^9.3.9

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

See context: https://github.com/jmcdo29/nest-commander/discussions/945#discussioncomment-6166115

**Comment by kamilmysliwiec** [comment]
> According to @jmcdo29, this library doesn't implement an OnModuleClose to handle closing the connection to bull or redis when the application shuts down.

This isn't correct.

https://github.com/nestjs/bull/blob/c47a7ccc8fa6e2795d3de9f2f98b0e14351031de/packages/bullmq/lib/bull.providers.ts#L67-L73
