### ISSUE TITLE
Bug Report - High Memory Usage when Providing Float to Concurrency in Bull.js Module

### ISSUE THREAD

**Issue by abdeljalil09** [nestjs/bull#1721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Description:
I encountered an issue while using the Bull.js module in Nest.js. When I provided a float value (5 / 2, which is 2.5) to the concurrency property in the processors configuration, I noticed a significant increase in memory usage.

Expected Behavior:
The concurrency value should be rounded to the nearest integer, as is the common practice in similar scenarios.

Reproduction Steps:

Import the BullModule from the Bull.js module in a Nest.js project.
Configure the registerQueue method with the following settings:

``

### Minimum reproduction code

https://gist.github.com/abdeljalil09/3aa76c9fab47b58f864604484c9b748e

### Steps to reproduce

Actual Results:
Upon providing 5 / 2 as the value for concurrency, the memory usage increases significantly, causing potential performance and stability issues.

### Expected behavior

I would expect the concurrency value to be rounded to the nearest integer, resulting in a value of 3 in this case (Math.round(5 / 2)).

### Package version

10.0.0

### Bull version

4.10.4

### NestJS version

10.0.4

### Node.js version

18.16.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the bull repository https://github.com/OptimalBits/bull
