### ISSUE TITLE
Upgrade bullmq peer dependecy to ^4.0.0

### ISSUE THREAD

**Issue by visomi-dev** [nestjs/bull#1728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to install the latest version of bullmq with the latest version of @nestjs/bullmq npm throws me a error:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @nestjs/bullmq@10.0.0
npm ERR! Found: bullmq@4.1.0
npm ERR! node_modules/bullmq
npm ERR!   bullmq@"^4.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer bullmq@"^3.0.0" from @nestjs/bullmq@10.0.0
npm ERR! node_modules/@nestjs/bullmq
npm ERR!   @nestjs/bullmq@"^10.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: bullmq@3.15.8
npm ERR! node_modules/bullmq
npm ERR!   peer bullmq@"^3.0.0" from @nestjs/bullmq@10.0.0
npm ERR!   node_modules/@nestjs/bullmq
npm ERR!     @nestjs/bullmq@"^10.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Minimum reproduction code

https://gist.github.com/visomi-dev/a857b68ef9698352ee42dfa294bea697

### Steps to reproduce

1. `npm install bullmq @nestjs/bullmq`

### Expected behavior

Install without errors

### Package version

10.0.0

### Bull version

4.2.0

### NestJS version

10.0.5

### Node.js version

16.20.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/bull/pull/1713
