### ISSUE TITLE
Multiple Processor on a same Queue?

### ISSUE THREAD

**Issue by captainjapeng** [nestjs/bull#173]
### Description
Is it possible to define multiple `@Processor` referencing the same Queue on different modules?

### Use Case
Sharing a Queue which is exported by a centralized `QueueModule`. Therefore I need to be able to define `@Process` to handle named jobs per module. 

### Current Behaviour
It seems that it just currently runs 1 of the 3 defined `@Process`, using 3 different queues seems to work properly

**Comment by kamilmysliwiec** [comment]
Fixed. Will be published as `@nestjs/bull`
