### ISSUE TITLE
How to dynamically modify the quantity of concurrency

### ISSUE THREAD

**Issue by longyanjiang** [nestjs/bull#1731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to know how to dynamically modify the number of concurrency and how to implement it if no similar API is found

### Minimum reproduction code

--

### Expected behavior

--

### Package version

--

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

--

**Comment by micalevisk** [comment]
### :warning: We use GitHub Issues to track bug reports, feature requests and regressions

Try the following instead:

- use our [Discord community](https://discord.gg/NestJS)  
  ![image](https://user-images.githubusercontent.com/13461315/193427207-c72f8b93-01a0-414f-a913-a572941d0442.png)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- make this question at [StackOverflow](https://stackoverflow.com/questions/ask?tags=nestjs) instead
