### ISSUE TITLE
Error with Bullmq Queue provider

### ISSUE THREAD

**Issue by Igorgro** [nestjs/bull#1748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm trying to build a nestjs application which uses BullMQ using official instruction (https://docs.bullmq.io/guide/nestjs), but getting the following error:

<details><summary>Details</summary>
<p>

```
[Nest] 806921  - 23.07.2023, 23:06:49   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AppController (?). Please make sure that the argument BullQueue_default at index [0] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If BullQueue_default is a provider, is it part of the current AppModule?
- If BullQueue_default is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing BullQueue_default */ ]
  })

Error: Nest can't resolve dependencies of the AppController (?). Please make sure that the argument BullQueue_default at index [0] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If BullQueue_default is a provider, is it part of the current AppModule?
- If BullQueue_default is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing BullQueue_default */ ]
  })

    at Injector.lookupComponentInParentModules (/home/igormahov/dev/nodejs/nest-bullmq/node_modules/@nestjs/core/injector/injector.js:254:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Injector.resolveComponentInstance (/home/igormahov/dev/nodejs/nest-bullmq/node_modules/@nestjs/core/injector/injector.js:207:33)
    at resolveParam (/home/igormahov/dev/nodejs/nest-bullmq/node_modules/@nestjs/core/injector/injector.js:128:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (/home/igormahov/dev/nodejs/nest-bullmq/node_modules/@nestjs/core/injector/injector.js:143:27)
    at Injector.loadInstance (/home/igormahov/dev/nodejs/nest-bullmq/node_modules/@nestjs/core/injector/injector.js:70:13)
    at Injector.loadController (/home/igormahov/dev/nodejs/nest-bullmq/node_modules/@nestjs/core/injector/injector.js:88:9)
    at /home/igormahov/dev/nodejs/nest-bullmq/node_modules/@nestjs/core/injector/instance-loader.js:68:13
    at async Promise.all (index 0)
```

</p>
</details> 

I noticed that the module created by `BullModule.registerQueue()` does not contains `BullQueue_default` provider (see `console.log` in attached repository). If I create a fake provider like that:
```
{
  provide: 'BullQueue_default'
  useValue: null
}
```
then the dependency injection for `@InjectQueue()` starts working. I think this is a bug in this library.

### Minimum reproduction code

https://github.com/Igorgro/nest-bullmq-bug

### Steps to reproduce

Create a minimal nestjs application using nest cli and add BullMQ here following the official instruction (https://docs.bullmq.io/guide/nestjs)

### Expected behavior

Dependency injection working well

### Package version

10.0.1

### Bull version

4.6.0

### NestJS version

10.1.0

### Node.js version

18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
that circular import you have between app.module and app.controller is leading to this

Move the line  
`export const QUEUE_NAME = 'myqueue'`  
to another file instead

**Comment by Igorgro** [comment]
Ok, thank you, that cycle dependency was the root cause of that exception
