### ISSUE TITLE
Support processor with observables

### ISSUE THREAD

**Issue by vahidvdn** [nestjs/bull#1788]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have an observable in my processor, as following:

```ts
@Processor(BULLMQ_QUEUE_NAME)
export class JobProcessor extends WorkerHost {
  async process(job: Job<Record<string, any>>): Promise<any> {
    this.client
      .send('testFailure', 5)
      .pipe(timeout(5000))
      .subscribe({
        next: (data) => console.log('successful job', data),
        error: (err) => console.log('failed job'), // can not fail the job
      });
  }
}
```

With promises, I can easily await a function, and based on my condition I can throw an error as the following and mark the job as `failed`:

```ts
throw new Error('job failed');
```

But with observables, I can't do this. If I put the `throw` inside the error section of observable, it doesn't work, because actually before that, the job is considered `completed`. 

**Note:** I prefer not to use `toPromise` since it's deprecated.

### Describe the solution you'd like

Any possible way to accomplish this issue

### What is the motivation / use case for changing the behavior?

Ability to use microservice client and in case of an issue with connection while sending the message, we could mark the job as failed.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
