### ISSUE TITLE
Support multiple rate limits

### ISSUE THREAD

**Issue by BarretteBanner** [nestjs/bull#1811]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

One requirement I often have is that some of the apis I am hitting have multiple rate limits. Bull only supports setting one in this way `  BullModule.registerQueue({
      name: 'fetch-xyz',
      limiter: {
        max: 100, // 100 jobs
        duration: 1000 // per second
      }
    }),`

Right now, I have to create 2 queues with their own limit. The processor for the first queue will then add a job to the 2nd queue. Such as ` BullModule.registerQueue({
      name: 'request-xyz',
      limiter: {
        max: 100, // 100 jobs
        duration: 1000 // per second
      }
    }),
    BullModule.registerQueue({
      name: 'request-xyz-slower',
      limiter: {
        max: 4000, // 4000 jobs
        duration: 60000 // per minute
      }
    })`

### Describe the solution you'd like

It would be really awesome if a queue could have multiple limiters such as `  BullModule.registerQueue({
      name: 'fetch-xyz',
      limiter: [ {
        max: 100, // 100 jobs
        duration: 1000 // per second
      }, 
 {
        max: 4000, 
        duration: 600000
      },]
    }),`

### What is the motivation / use case for changing the behavior?

This change would allow developers to develop against multiple rate limit requirements using a single queue.

**Comment by kamilmysliwiec** [comment]
I'd suggest reporting this issue in the bull repository (official bull repo)
