### ISSUE TITLE
Support BullMQ v5.0.0

### ISSUE THREAD

**Issue by EricDunaway** [nestjs/bull#1945]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

BullMQ version 5 is not supported due to breaking changes.

BullMQ requires the connection information to be provided to queue options. This package does not automatically reuse the connection information passed in the Module Registration.

### Describe the solution you'd like

Full support for version 5
- fix the issue with registerQueue requiring connection info
- fix any other issues

### What is the motivation / use case for changing the behavior?

To continue to use the latest version of BullMQ in my projects

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by vsamofal** [comment]
Hi @kamilmysliwiec , PR is ready https://github.com/nestjs/bull/pull/1960

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/bull/pull/1960
