### ISSUE TITLE
options.family is not cast to number if given in REDIS_URL

### ISSUE THREAD

**Issue by nktnet1** [nestjs/bull#2001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using a REDIS_URL with a family query parameter, e.g.
```text
REDIS_URL="redis://@redis:6379/?family=4"
```

and in Nestjs:

```typescript
    BullModule.forRootAsync({
      inject: [ConfigService],
      useFactory: async (
        configService: ConfigService,
      ): Promise<BullModuleOptions> => ({
        redis: configService.getOrThrow('REDIS_URL'),
      }),
    }),
```

an error is thrown:
```text
TypeError: The property 'options.family' must be one of: 0, 4, 6. Received '4'
    at lookup (node:dns:179:11)
    at emitLookup (node:net:1405:5)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
    at lookupAndConnectMultiple (node:net:1404:3)
    at node:net:1350:7
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
    at lookupAndConnect (node:net:1349:5)
    at Socket.connect (node:net:1246:5)
    at connect (node:net:236:17)
```

### Minimum reproduction code

https://github.com/nktnet-bug-report/nestjs-bull-bug

- forked from [nestjs/typescript-starter](https://github.com/nestjs/typescript-starter)
- added code from [nest/sample/26-queues](https://github.com/nestjs/nest/tree/master/sample/26-queues)

### Steps to reproduce

1. npm i
2. npm start

### Expected behavior

No error, i.e. options.family is correctly type-casted to number.

### Package version

10.1.0

### Bull version

4.12.2

### NestJS version

10.3.2

### Node.js version

21.6.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

![nestjs-bull-bug](https://github.com/nestjs/bull/assets/86177399/0cd9be41-9c42-4c68-8809-7be4dfee095a)

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the bull repository (not nestjs wrapper)
