### ISSUE TITLE
NestJS Bull appears to be utilizing Upstash Redis unnecessarily.

### ISSUE THREAD

**Issue by dsmabulage** [nestjs/bull#2029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

NestJS Bull utilises Upstash Redis unnecessarily, even when not using the queues. This behaviour results in unnecessary resource consumption and increased costs.

### Minimum reproduction code

-

### Steps to reproduce

```
BullModule.registerQueue({
      name: QUEUE_NAME,
      defaultJobOptions: {
        delay: 5000,
        removeOnComplete: true,
        removeOnFail: true,
        attempts: 3,
      },
    }),
 ```
 
 Bull module
 
 ```
 BullModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory(configService: ConfigService) {
           return {
            redis: {
              host: `${configService.get('REDIS_HOST')}:${configService.get(
                'REDIS_PORT',
              )}
                `,
              port: configService.get('REDIS_PORT'),
              password: configService.get('REDIS_PASSWORD'),
              tls: {
                rejectUnauthorized: true,
                host: configService.get('REDIS_HOST'),
                port: configService.get<number>('REDIS_PORT'),
              },
            },
          };      },
    })
    ```

### Expected behavior

NestJS Bull should only utilize Upstash Redis when actively using the queues for job processing.

### Package version

10.1.0

### Bull version

4.12.2

### NestJS version

10.0.0

### Node.js version

20.11.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
This package doesn't use Upstash
