### ISSUE TITLE
Ability to accept/reject jobs before being processed

### ISSUE THREAD

**Issue by ajfranzoia** [nestjs/bull#2039]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have a microservices architecture where there's a media service in charge of processing media files. This service receives jobs to process in a certain queue, and the caller microservice awaits for the result. I'm trying to change this scheme to a more robust one, as suggested in the documentation, and use a results queue to post results.

The problem that I can see with this approach is that there's no way to deterministically handle the result job by the service that actually made the request. For example, if I have service A and service B, that both requests jobs to the media service and wait for results to be posted to the results queue, it could happen that service B processed a result job that was originally requested by A.

### Describe the solution you'd like

It would be nice to allow the worker to indicate if the job can be processed without the need to create additional queues.

### What is the motivation / use case for changing the behavior?

Possibility to accept/reject jobs by a worker without the need to create additional result queues.

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
