### ISSUE TITLE
"Connection is closed" jest error when using bullmq > 5.1.11

### ISSUE THREAD

**Issue by trhodeos** [nestjs/bull#2138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running a simple test in jest (spin up an application with a queue and a WorkerHost) and tearing down the app, we see unhandled errors from jest: `Connection is Closed`.

I tracked this down to this ticket / PR on the bullmq side: https://github.com/taskforcesh/bullmq/issues/2385.

### Minimum reproduction code

https://github.com/trhodeos/bull

### Steps to reproduce

1. yarn install
1. cd packages/bullmq
1. yarn test:e2e

### Expected behavior

Tests run sucessfully

### Package version

10.1.1 (bullmq)

### Bull version

5.1.12 (bullmq)

### NestJS version

10.3.0

### Node.js version

18.20.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by trhodeos** [comment]
For a "fix", I've pinned bullmq to 5.1.11. However, it would be nice to be on the latest bullmq.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by JacobReynolds** [comment]
I've been running into this issue as well, bullmq says the [issue is fixed](https://github.com/taskforcesh/bullmq/issues/2385) however upgrading to the latest version of bull does not appear to help.

**Comment by TiagoAndreAlmeida** [comment]
i can confim the bug still there.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/bull/pull/2294
