### ISSUE TITLE
Issue with @InjectQueue decorator when used in a class that extends another class

### ISSUE THREAD

**Issue by kziya** [nestjs/bull#2142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the `@InjectQueue` decorator in the constructor of a class that extends another class, the NestJS IoC container incorrectly injects the queue into both the decorated argument and another argument before the decorated one.

### Minimum reproduction code

https://github.com/kziya/nestjs-bull-module-injection-issue

### Steps to reproduce

1. yarn
2. npm run start:dev
3. open the logs in the  app.service.ts constructor 

### Expected behavior

The `appRepository` should be an instance of `AppRepository`, and `testQueue` should be an instance of `Queue`. The `testQueue` should be correctly injected and passed to the `AppSharedService` constructor.

### Package version

10.1.1

### Bull version

4.14.0

### NestJS version

10.0.0

### Node.js version

22.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

<img width="1699" alt="Screenshot 2024-06-26 at 15 02 29" src="https://github.com/nestjs/bull/assets/58106222/f82c1cc3-d8af-4d82-a513-9f9fdaaef1c3">

**Comment by micalevisk** [comment]
btw this is not related with `@nestjs/bull` but `@nestjs/core`

**Comment by kziya** [comment]
I discovered that this issue only occurs when using the `@Inject` decorator in the constructor of the shared class. Therefore, I don't believe this is a limitation of the framework; however, I will report it to the `nestjs/core` team for further investigation.
