### ISSUE TITLE
Queue Processor Not Closing in E2E Test Modules

### ISSUE THREAD

**Issue by Rcuz8** [nestjs/bull#2168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

E2E tests will never exit when using NestJS Queues: https://docs.nestjs.com/techniques/queues.

### Minimum reproduction code

https://github.com/Rcuz8/nestjs-queues-bug

### Expected behavior

The e2e tests should exit

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/bullmq

### NestJS version

10.4.2

### Packages versions

```json
"dependencies": {
    "@nestjs/bullmq": "^10.1.1",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.2.3",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "bullmq": "^5.10.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1"
  },

```

### Node.js version

20.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
You need to call `await app.close()` in the afterAll/afterEach hook
