### ISSUE TITLE
Processor/Job doesn't run when testing Queues

### ISSUE THREAD

**Issue by VictorGaiva** [nestjs/bull#227]
## I'm submitting a...
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When in testing environment (Eg. jest), any `Process` doesn't run at all. The job is added to the Queue, `Processor` is instantiated and the compiler is able to detect that the handler for a specific job Name exists, but the following Promise never resolves (timeout):

```typescript
new Promise(res => queue.add('test', 'data').then(job => job.finished().then(result => {
  expect(result).toBe(job.data);
  res();
})));
```

## Expected behavior

The promise should resolve with the expected data.

## Minimal reproduction of the problem with instructions

https://github.com/VictorGaiva/BullTestingIssue

## What is the motivation / use case for changing the behavior?

We should be able to test `@nestjs/bull` jobs for expected behavior. 

## Environment

<pre><code>
Nest version: "@nestjs/core": "^6.7.2"
 
For Tooling issues:
- Node version: 13.2.0
- Platform:  Linux (Ubuntu 19.10)

Others:
Reproduction repository generated using `@nestjs/cli`

**Comment by kamilmysliwiec** [comment]
You can follow this example: https://github.com/nestjs/bull/blob/master/e2e/module.e2e-spec.ts which seems to solve the same problem as you described

**Comment by VictorGaiva** [comment]
The example uses `jest.fn()` to mock the `Consumer`, seen [here](https://github.com/nestjs/bull/blob/d54274d2a6f3090a594b389e5d54500ebad556df/e2e/module.e2e-spec.ts#L144).

There repo has two test scripts:
* [app.module.spec.ts](https://github.com/VictorGaiva/BullTestingIssue/blob/master/src/app.module.spec.ts) which tests if the message was added to the Queue and processed by the mockFn, as done in the example. It uses a `app.controller.ts` to adds a job, which is done as a side effect.
* [app.processor.spec.ts](https://github.com/VictorGaiva/BullTestingIssue/blob/master/src/app.processor.spec.ts) which retrieves the Queue itself, manually adds the job and creates a Promise to `expect` the job to return the same data I sent.

The second is the one attempts to use the Process defined in `app.processor.ts`. The example you linked doesn't cover this case. It uses mock functions in all tests.

**Comment by kamilmysliwiec** [comment]
We bind processors on the `onModuleInit` hook. To trigger it, you have to call `await app.init()` after `compile()`

**Comment by VictorGaiva** [comment]
Yep that's it. Thanks. 

I believe it would be convenient to add this piece of information to the `@nestjs` Queues documentation. 

It now raises another question. What other modules require a the module to be inita

**Comment by radacat2121** [comment]
> https://github.com/nestjs/bull/blob/master/e2e/module.e2e-spec.ts

forgive me, the provided link is not working anymore :(
