### ISSUE TITLE
npm package version does not match with release version

### ISSUE THREAD

**Issue by nguyenlc1993** [nestjs/bull#234]
I have some questions regarding to release versions:
1. At this time, the latest release on this repository is `0.9.0`, while the latest npm package version is `0.0.1-beta.4`. Is there any correlation between releases on this repository and published npm package versions?
2. Which commit corresponds to the latest package version of `0.0.1-beta.4`?
3. When will semantic release be implemented for this module?

Besides, is it recommended to use this module on production yet? My current project is using NestJS, and I already have implemented queue service with Bull. However the techniques described in NestJS document looks promising, so I want to try out this module if possible.

Thank you for your support.

**Comment by kamilmysliwiec** [comment]
> At this time, the latest release on this repository is 0.9.0

These are legacy releases (before migrating `bull` package under the official organization). I just removed them!

> Which commit corresponds to the latest package version of 0.0.1-beta.4?

The latest release is on master.

> When will semantic release be implemented for this module?

I just published 0.0.1.

> Besides, is it recommended to use this module on production yet

Feel free to use it in production. This module is just a wrapper around the `bull` package.
