### ISSUE TITLE
Integrate the newly added `bullmq-otel` opentelemetry instrumentation module

### ISSUE THREAD

**Issue by mali-13** [nestjs/bull#2370]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to integrate the newly added `bullmq-otel` described [here](https://docs.bullmq.io/guide/telemetry/getting-started) in the official BullMq website.

The module provides a working implementation of BullMQ's telemetry interface for the OpenTelemetry standard. 

This does not seem to be possible in the `@nestjs/bull` yet

### Describe the solution you'd like

It would be nice to enable this for each queue and worker. Something like

```
BullModule.registerQueue({
      name: QUEUE_NAMES.DRIVER_CHANGE_SYNC,
      telemetry: new BullMQOtel('simple-guide'),
}),
```

An option to enable this for all queues and workers would also be nice.

### What is the motivation / use case for changing the behavior?

It would be great to have an easy way to integrate opentelemetry autoinstrumentation for nesjts bullmq queues.

**Comment by micalevisk** [comment]
I guess this is supposed to be supported already as the queue options for `registerQueue` are from `bullmq` itself:  https://github.com/nestjs/bull/blob/c1f1bb01066f0eebfbbc875ac3e3133006c10d92/packages/bullmq/lib/interfaces/register-queue-options.interface.ts#L7-L12

**Comment by kamilmysliwiec** [comment]
See @micalevisk response
