### ISSUE TITLE
BullModule error circular dependency

### ISSUE THREAD

**Issue by flohub21** [nestjs/bull#267]
Hello,

I have this error  of circular dependency with the BullModule (@nestjs/bull).

![image](https://user-images.githubusercontent.com/43141923/74164025-7d6bbb00-4c23-11ea-863f-6416b0885875.png)

**My code** 

app.module.ts : 
![app_module](https://user-images.githubusercontent.com/43141923/74164268-d5a2bd00-4c23-11ea-8a19-6d35019da716.png)

**Environment **

package.json : 

![image](https://user-images.githubusercontent.com/43141923/74164627-53ff5f00-4c24-11ea-9b1d-3e63c790e636.png)

Node version : v10.16.0

Thank's you.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by flohub21** [comment]
Here's my depo :)
https://github.com/flohub21/bullmodule

**Comment by fwoelffel** [comment]
I couldn't reproduce. Here's what I did (with a running instance of Redis):
```bash
git clone git@github.com:flohub21/bullmodule.git
cd bullmodule
npm install
npm start
```

**Comment by germansokolov13** [comment]
I had the same problem. It has to do with old NestJS version. Updating from `6.7` to `6.11` solved the issue for me.

**Comment by ngtrieuvi92** [comment]
> I had the same problem. It has to do with old NestJS version. Updating from `6.7` to `6.11` solved the issue for me.

awesome. it works perfectly  after upgrade to `6.11`

**Comment by manendrabhel** [comment]
Yes It works perfect after upgrade nestjs version. But might be possibility you get another errors like : `node_modules/@nestjs/common/http/http.service.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.
13     get axiosRef(): AxiosInstance;` . To resolve this you can upgrade typescript if not upgraded before to latest one.
