### ISSUE TITLE
Empty jobs created when a lot of jobs added

### ISSUE THREAD

**Issue by uncledent** [nestjs/bull#284]
``` 
for (const user of users) {
      // todo: emit added to queue
      try {
        const job = this.importQueue.add(
          'import-user',
          {
            user,
            transactionId,
            tenantId,
          } as UserImportJobData,
          {
            removeOnComplete: true,
            removeOnFail: true,
          },
        );
      } catch (error) {
        console.error(error, 'add-jobs-to-queue');
      }
    }
```

## Current behavior
Add 1350 jobs to the queue -> jobs created, but many of them have __default__ name and no data,  I also cant find those in the REDIS

Here is a screenshot of the paused queue, as you see some jobs are missing data and index (12,50,59). 

<img width="1369" alt="Bildschirmfoto 2020-02-23 um 23 48 58" src="https://user-images.githubusercontent.com/6542981/75121730-17594c00-5697-11ea-9650-5839c191d27d.png">

The more to the list end, the more jobs are corrupt:

<img width="1377" alt="Bildschirmfoto 2020-02-23 um 23 53 09" src="https://user-images.githubusercontent.com/6542981/75121794-acf4db80-5697-11ea-9df2-ff78e80fb427.png">

## Expected behavior
All jobs must be created with data inside and right name

## Environment
    "@nestjs/bull": "0.0.3",
    "@nestjs/common": "^6.11.7",
    "@nestjs/core": "^6.11.7",
   "bull": "^3.13.0",

For Tooling issues:
node v10.16.2
- Platform:  Mac

Any idea to dig into? Maybe the queue is not ready? Or some limit?

Thank you in advance!

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the [bull](https://github.com/OptimalBits/bull) repository.
