### ISSUE TITLE
Add example for multiple async configurations

### ISSUE THREAD

**Issue by fwoelffel** [nestjs/bull#29]

**Comment by smonv** [comment]
Can you provide example async configuration with custom queue name and `@Queue` decorator ?

**Comment by fwoelffel** [comment]
Hi @smonv 	
I'm sorry such a trivial task take me so long. I'll try to close this as soon as I find some time to do so. Until then, this may help you https://github.com/fwoelffel/nest-bull/issues/13#issuecomment-480098920.

**Comment by smonv** [comment]
Hi @fwoelffel , thank you for suggestion.

I'm trying to use `Queue` decorator to define a class and processor and I want inject many service to that class. Do I need inject all the service when define `BullModule.forRootAsync` ?

**Comment by fwoelffel** [comment]
Hi @smonv, I'm really sorry that it took me so long to notice your answer.
If you're using the `@Queue` decorator, you can inject the services you need into the targeted class. This is a simple Nest injection and should have nothing to do with `BullModule.forRootAsync` :)

If you're still having trouble with this, I'll try to help you in much shorter terms.

**Comment by smonv** [comment]
Thank for your response. I'll use nest-bull again soon in my project and
notify you about update.

**Comment by anitricks** [comment]
@fwoelffel hi there, i just started to use nest-bull but i am having problems with injecting services and using it inside the queue process function. Following the example you wrote I can't even access the logger. Neither the service or the logger are available in the queue. 

Is this a scope problem? the queue is in the Users Module, and there is a User Service which I need to access inside the queue. So all of them are in the UsersModule, and the Service and Queue are in providers with BullModule being imported in the imports section of the UsersModule

`@Module({
  imports: [
    BullModule.forRoot({
      name: 'user',
      options: {
        redis: {
          port: 0000
        }
      }
    }),
  ],
  providers: [
    UsersService,
    UsersQueue
  ],
  controllers: [UsersController],
  exports: [UsersService]
})`

**Comment by fwoelffel** [comment]
@anitricks That should work :thinking: Could you also share your `UsersService`

**Comment by anitricks** [comment]
@fwoelffel yeah sure. here is the service below. Thanks for the quick response
`@Injectable()
export class UsersService extends Entity<User> {

    constructor(
        @InjectRepository(User) repo: Repository<User>,
        connection: Connection
    ) {
        super(repo, connection);
    }

    findUsers(params: { firstname?: string, lastname?: string, dob?: string }) {
        //
    }
}`

its very weird. i've been scratching my head. I also have tried to put the UserQueue in the Application Module and injecting the Queue in Application Controller, however is was the same problem. Do I have to try `forRootAsync` because of the TypeORM module?

**Comment by fwoelffel** [comment]
I don't see any issue with your code... :thinking: Since we are drifting away from the original topic, would you be kind enough to create a new issue?

**Comment by anitricks** [comment]
yeah sorry about that. i will create a new issue

**Comment by kamilmysliwiec** [comment]
We'll cover all that in the documentation https://github.com/nestjs/docs.nestjs.com/issues/883
