### ISSUE TITLE
[Question] Interceptors

### ISSUE THREAD

**Issue by gperdomor** [nestjs/bull#429]
Is possible use interceptors in processors?

**Comment by kamilmysliwiec** [comment]
Enhancers aren't supported (and there's no plan to do so)

**Comment by WonderPanda** [comment]
@kamilmysliwiec I have a use case where having interceptors on processors would be super useful. Is this not being supported due to technical reasons or is it just an issue of time and effort due to their being lower demand for this?

**Comment by vhermecz** [comment]
Support for interceptors would be ideal to add handlers (logging, sentry) for unhandled exceptions.
