### ISSUE TITLE
Unable to use BullModule forRoot or forRootAsync

### ISSUE THREAD

**Issue by mateusmlo** [nestjs/bull#637]
## I'm submitting a...

- [ ] Regression 
- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request

## Current behavior
I'm currently following the docs to implement Bull queues on my project, but upon trying to import it on my app.module.ts it seems the forRoot function is not available anymore.
`Property 'forRoot' is private and only accessible within class 'BullModule'.ts(2341)`

## Expected behavior
I should be able to use `BullModule.forRoot` or `forRootAsync` just like in the docs, but I don't know if they are outdated.

## Minimal reproduction of the problem with instructions
Simply import BullModule and use it on the imports array and TS will act up.
```
import { Module } from '@nestjs/common';
import { BullModule } from '@nestjs/bull';

@Module({
  imports: [
   // error is on line below
    BullModule.forRoot({
      redis: {
        host: 'localhost',
        port: 6379,
      },
    }),
  ],
})
export class AppModule {}
```

## What is the motivation / use case for changing the behavior?
The BullModule currently only exposes registerQueue and registerQueueAsync methods, while the docs clearly uses other methods that won't compile (the ones I described in Expected behavior).

## Environment
Nest version: 7.0.0

 For Tooling issues:
- Node version: 15.0.1
- Platform:  Windows/Linux (WSL 2)

Others: VS Code

**Comment by ignaion** [comment]
I have the same issue.
can you tell me, how do you fix this?

**Comment by mateusmlo** [comment]
> I have the same issue. can you tell me, how do you fix this?

Which version of @nestjs/bull are you using? I'm sorry it's been so long I don't really remember how I fixed it, should have documented it here 😕
Here TS sugests the other two methods you are looking for. This project uses version ^0.3.0, try updating to the latest.
![image](https://user-images.githubusercontent.com/13263031/151974295-f6bc7b93-c59e-421c-9b9a-8b89771845af.png)
