### ISSUE TITLE
Add Documentation About bull-board

### ISSUE THREAD

**Issue by henriqueleite42** [nestjs/bull#675]
## I'm submitting a...

- [x] Documentation issue or request

## What is the motivation / use case for changing the behavior?

Hello guys, first of all, thanks for the awesome lib, it helps a lot! :smile: 

Now, about this issue, I'm missing documentation about how to integrate the bull-board, mainly using controllers with guards.

If you guys have some time, can you add documentation about it, please?

**Comment by vh13294** [comment]
I think bull-board (bull-ui) only available in version 3.

**Comment by vh13294** [comment]
I hope this would help.

https://stackoverflow.com/q/63271404

**Comment by Tony133** [comment]
Hi @henriqueleite42, for next time, if your questions are about documentation open them in this repository: https://github.com/nestjs/docs.nestjs.com

**Comment by henriqueleite42** [comment]
Hi @Tony133,

Thanks for the awnser, I created [the issue](https://github.com/nestjs/docs.nestjs.com/issues/1688) there :smile:

**Comment by kamilmysliwiec** [comment]
`bull-board` is a separate, non-required package. To integrate it with Nest, follow instructions in their README - it should be pretty straightforward.
