### ISSUE TITLE
How to publish job from another app?

### ISSUE THREAD

**Issue by ahmadarif** [nestjs/bull#7]
I want to publish job from another app (like express), and process it in nest. How to deal with it?

**Comment by fwoelffel** [comment]
You can either expose an endpoint from your nest application (see the quickstart example), or you can send a job to your redis instance from your another app. If you choose to go with the second solution, consider looking at https://github.com/OptimalBits/bull.

This module is basically a wrapper around OptimalBits' `bull` library.
