### ISSUE TITLE
The useClass of BullModule.forRootAsync seems to have incorrect type

### ISSUE THREAD

**Issue by RRGT19** [nestjs/bull#723]
## Bug Report

`Type 'typeof AppService' is not assignable to type 'Type<SharedBullConfigurationFactory>'.   Property 'createSharedConfiguration' is missing in type 'AppService' but required in type 'SharedBullConfigurationFactory'.`

## Current behavior
According to the official guide [here](https://docs.nestjs.com/techniques/queues#async-configuration), if we use:
```typescript
BullModule.forRootAsync({
  useClass: BullConfigService,
});
```

and

```typescript
@Injectable()
class BullConfigService implements BullOptionsFactory {
  createBullOptions(): BullModuleOptions {
    return {
      redis: {
        host: 'localhost',
        port: 6379,
      },
    };
  }
}
```

I receives the error above.

Navigating to the `shared-bull-config.interface.d.ts`, I see that `useClass` has a different type, and not the one that the guide says to use:
```
export interface SharedBullAsyncConfiguration extends Pick<ModuleMetadata, 'imports'> {
    useClass?: Type<SharedBullConfigurationFactory>; // <---
}
```

To make it work I need to do:
```
@Injectable()
class BullConfigService implements SharedBullConfigurationFactory { // <---
  createSharedConfiguration(): Promise<Bull.QueueOptions> | Bull.QueueOptions { // <---
    return {
      redis: {
        host: 'localhost',
        port: 6379,
      },
    };
  }
}
```

## Expected behavior | Possible Solution
The `useClass` of `BullModule.forRootAsync()` to be of type `BullOptionsFactory`.

## Environment

Nest version: 7.5.6

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/bull/pull/726#issuecomment-801108967
