### ISSUE TITLE
Support for new JobFlow 

### ISSUE THREAD

**Issue by Pietrox** [nestjs/bull#754]
## I'm submitting a... feature request

taskforcesh/bullmq#454 - new Job Flow feature topic
taskforcesh/bullmq#468 - issue that I found out it's regarding nestjs/bull instead of the update

When using the standard:

```
constructor(@InjectQueue('QueueName') private readonly flow: Flow){}
```
The formula correctly injects the Queue but it will not allow to register the Parent/Child queue properly with their names provided like in new feature documentation: 

https://docs.bullmq.io/guide/jobs/parent-child-jobs

Regarding bullmq vs bull package, both work really well by using the "Queue" class.

**Comment by kamilmysliwiec** [comment]
This package currently does not support `bullmq` library. Also, it's very likely we'll eventually publish a separate integration (outside of this package) instead of deprecating the `bull` itself (to avoid breaking changes).
