### ISSUE TITLE
Async config doesn't work with bull@v3.25.0

### ISSUE THREAD

**Issue by ptrkcsk** [nestjs/bull#874]
## I'm submitting a...

<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

1. Run Redis somewhere *other than* `localhost:6379`, e.g. `localhost:6380`
1. Get Redis connection credentials from [`ConfigService`](https://docs.nestjs.com/techniques/configuration) via [`BullModule` async config](https://docs.nestjs.com/techniques/queues#async-configuration)
1. Start app
1. Bull tries, and fails, to connect to a default URL `127.0.0.1:6379` instead of the one from `ConfigService`
    
Full error message:

```
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)
```

## Expected behavior

Bull should connect to the URL specified from `ConfigService`

## Minimal reproduction of the problem with instructions

1. Clone [my fork of NestJS](https://github.com/ptrkcsk/nest):
    ```sh
    git clone git@github.com:ptrkcsk/nest.git
    ```
1. Navigate to Bull sample:
    ```sh
    cd sample/26-queues
    ```
1. Switch to `master`:
    ```sh
    git switch master
    ```
1. Install dependencies:
    ```sh
    npm install
    ```
1. Start the app
    ```sh
    npm run start:dev
    ```
1. There will be an `ECONNREFUSED` error message if Redis isn't running locally on port 6379. This is okay. We'll use this error message to determine which Redis URL Bull is trying to connect to. Confirm that the `ECONNREFUSED` error message contains the correct Redis host and port, `127.0.0.1:6379`, which are set in the [`BullModule` import](https://github.com/ptrkcsk/nest/blob/e0bfe8dbda3c687d01debbdffe18e2dd9d1953e2/sample/26-queues/src/app.module.ts#L11-L12).
1. Switch to the branch which gets the Redis URL from `ConfigService`:
    ```sh
    git switch redis-config-bull
    ```

    [Diff between `master` and `redis-config-bull`](https://github.com/ptrkcsk/nest/compare/master...redis-config-bull)
1. Repeat steps 4-5
1. Confirm that Bull tries to connect to the wrong URL: `127.0.0.1:6379`. It should try to connect to the URL set in `.env`: `127.0.0.1:6380`.
1. Switch to the branch which downgrades `bull` to v3.25.0:
    ```sh
    git switch redis-config-bull-3_25_0
    ```

    [Diff between `redis-config-bull` and `redis-config-bull-3_25_0`](https://github.com/ptrkcsk/nest/compare/redis-config-bull...redis-config-bull-3_25_0)
1. Repeat steps 4-5
1. Confirm the problem in step 9 persists
1. Switch to the branch which downgrades `bull` to v3.24.0:
    ```sh
    git switch redis-config-bull-3_24_0
    ```

    [Diff between `redis-config-bull` and `redis-config-bull-3_24_0`](https://github.com/ptrkcsk/nest/compare/redis-config-bull...redis-config-bull-3_24_0)
1. Repeat steps 4-5
1. Confirm that Bull now tries to connect to the correct URL set in `.env`: `127.0.0.1:6380`

## Environment

<pre><code>
Nest version: 8.0.5
 
For Tooling issues:
- Node version: 16.6.0
- Platform:  Mac, Linux
</code></pre>

**Comment by ptrkcsk** [comment]
Related: https://github.com/nestjs/bull/issues/10

**Comment by kamilmysliwiec** [comment]
Duplicate https://github.com/nestjs/bull/issues/869
