### ISSUE TITLE
Fix BullModuleAsyncOptions interface

### ISSUE THREAD

**Issue by fwoelffel** [nestjs/bull#94]
- ~~According to the [`Provider`](https://github.com/nestjs/nest/blob/master/packages/common/interfaces/modules/provider.interface.ts#L5) interface, the [`BullModuleAsyncOptions.useExisting`](https://github.com/fwoelffel/nest-bull/blob/587175c2a61cbb25165734549d440b8a2889ef6d/lib/bull.interfaces.ts#L18) support should be removed~~ See https://github.com/nestjs/nest/pull/2262
- According to the [`Provider`](https://github.com/nestjs/nest/blob/master/packages/common/interfaces/modules/provider.interface.ts#L22) interface, the [`BullModuleAsyncOptions.inject`](https://github.com/fwoelffel/nest-bull/blob/587175c2a61cbb25165734549d440b8a2889ef6d/lib/bull.interfaces.ts)  should become `string | symbol | Type<any> | Abstract<any> | Function` or `FactoryProvider['inject']` _(need to check this with the NestJS maintainers since there is a mismatch with the `provide` properties)_
- The [`BullModuleAsyncOptions.useClass`](https://github.com/fwoelffel/nest-bull/blob/587175c2a61cbb25165734549d440b8a2889ef6d/lib/bull.interfaces.ts#L19) type should be `Type<Omit<BullModuleOptions, 'name'>>` or `ClassProvider<Omit<BullModuleOptions, 'name'>>['useClass']`
- The [`BullModuleAsyncOptions.useFactory`](https://github.com/fwoelffel/nest-bull/blob/587175c2a61cbb25165734549d440b8a2889ef6d/lib/bull.interfaces.ts#L20) type should be `(...args: any[]) => Promise<Omit<BullModuleOptions, 'name'>> | Omit<BullModuleOptions, 'name'>` or `FactoryProvider<Omit<BullModuleOptions, 'name'>>['useFactory']`_(need to check the Promise support with the NestJS maintainers)_

--- 

```ts
export interface BullModuleAsyncOptions
  extends Pick<ModuleMetadata, 'imports'> {
  name?: string;
  useClass?: Type<BullModuleOptions>;
  useFactory?: (
    ...args: any[]
  ) => Promise<BullModuleOptions> | BullModuleOptions;
  inject?: any[];
}
```
could (or _should_) become
```ts
export interface BullModuleAsyncOptions {
  name?: BullModuleOptions['name'];
  imports?: ModuleMetadata['imports'];
  useClass?: ClassProvider<Omit<BullModuleOptions, 'name'>>['useClass'];
  useFactory?: FactoryProvider<Omit<BullModuleOptions, 'name'>>['useFactory'];
  inject?: FactoryProvider['inject'];
}
```

Note: `Omit` seems to make the remaining keys mandatory

**Comment by fwoelffel** [comment]
```ts
export interface BullModuleAsyncOptions
  extends Pick<ModuleMetadata, 'imports'> {
  name?: string;
  useClass?: Type<BullModuleOptions>;
  useFactory?: (
    ...args: any[]
  ) => Promise<BullModuleOptions> | BullModuleOptions;
  inject?: any[];
}
```
should become
```ts
export interface BullModuleAsyncOptions {
  name?: BullModuleOptions['name'];
  imports?: ModuleMetadata['imports'];
  useClass?: Type<Omit<BullModuleOptions, 'name'>>;
  useFactory?: (
    ...args: any[]
  ) =>
    | Promise<Omit<BullModuleOptions, 'name'>>
    | Omit<BullModuleOptions, 'name'>;
  inject?: any[];
}
```

**Comment by kamilmysliwiec** [comment]
Fixed
