### ISSUE TITLE
 Error Nest cant resolve dependencies of the BullExplorer

### ISSUE THREAD

**Issue by ramandhingra** [nestjs/bull#954]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the regression

When I run the Nestjs server, I get the following error. I am using the NestJS BullModule.

Error: Nest can't resolve dependencies of the BullExplorer (?, DiscoveryService, BullMetadataAccessor, MetadataScanner) Please make sure that the argument ModuleRef at index [0] is available in the BullModule context.

Potential solutions:

If ModuleRef is a provider, is it part of the current BullModule?
If ModuleRef is exported from a separate @Module, is that module imported within BullModule? @Module({ imports: [ /* the Module containing ModuleRef */ ] })

### Minimum reproduction code

```ts

```

### Expected behavior

The Nest Server should not stop and display this error. Instead, it starts listening to the incoming requests.

### Other

Main nestjs/ packages I am using are: "@nestjs/bull": "^0.4.1", "@nestjs/common": "8.0.11", "@nestjs/config": "1.0.2", "@nestjs/core": "8.0.11", "@nestjs/graphql": "9.0.5", –

**Comment by ramandhingra** [comment]
If anyone can give a hint, what could be the source of problem, it'd help me. Does it have anything to do with the NestJs version 8, or a bug in Bull module, or something wrong at me end.

Thanks.

**Comment by ramandhingra** [comment]
Thanks @micalevisk 

Here is the link to the repository:
https://github.com/fivethree-team/nestjs-prisma-starter

Kindly upgrade all the modules listed in package.json to the latest versions. Also add the nestjs/bull module.

**Comment by ramandhingra** [comment]
Pl. upgrade the entire repo. to their latest versions. Mine are :  "@nestjs/bull": "^0.4.1", "@nestjs/common": "8.0.11", "@nestjs/config": "1.0.2", "@nestjs/core": "8.0.11", "@nestjs/graphql": "9.0.5",

My `@nestjs/core `is: 8.0.11 while your is: 8.0.6

**Comment by micalevisk** [comment]
> My @nestjs/core is: 8.0.11 while your is: 8.0.6

actually, mine is 8.0.11 as well

![image](https://user-images.githubusercontent.com/13461315/136665873-d748561c-1538-40f8-9903-4d4e5c9615c7.png)

---

looks like this is not a bug. Please use [discord](https://discord.gg/nestjs) for this or provide a repo that reproduces your issue.

**Comment by ramandhingra** [comment]
Thanks for the help @micalevisk

Yesterday I had written this issue on discord as well.

When you said "looks like this is not a bug", do you mean that there is no bug in Nest JS and Bull module code?

**Comment by micalevisk** [comment]
> I had written this issue on discord as well.

I didn't find it there. Can you leave the link for your message here?

> do you mean that there is no bug in Nest JS and Bull module code?

no. I meant this seems to be some misconfiguration on your side. Maybe this is not even related to `@nestjs/bull` but I can't tell much since I didn't manage to reproduce this.

**Comment by kamilmysliwiec** [comment]
This seems to be a configuration issue on your side. I couldn't reproduce it either.
